log:
  level: debug
providers:
  file:
    directory: /etc/traefik
    watch: true
api:
  insecure: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
middlewares:
  log-wasm-wat:
    middlewares:
      - wasm-wat@file
  log-wasm-go:
    middlewares:
      - wasm-go@file
experimental:
  localPlugins:
    wasm-go:
      moduleName: wasm-go
    wasm-wat:
      moduleName: wasm-wat