name: build-on-command

on:
  workflow_dispatch:
# push:
#   paths:
#     - Dockerfile
#     - Makefile
#     - '.github/workflows/build-on-commit.yaml'

env:
  PLATFORMS: linux/arm/v7,linux/arm64,linux/amd64

permissions:
  packages: write
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    -
      name: Do Checkout
      uses: actions/checkout@v4
    - 
      name: Allow `git`
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    -
      name: Set up QEMU need for cross-platform building
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ env.PLATFORMS }}
    -
      name: Set up for "docker buildx"
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ env.PLATFORMS }}
    -
      name: Install TinyGo
      run: |
        wget --progress=dot:mega https://github.com/tinygo-org/tinygo/releases/download/v0.31.2/tinygo_0.31.2_amd64.deb
        sudo dpkg -i tinygo_0.31.2_amd64.deb
    -
      name: Install Grain
      run: |
        sudo curl -L --output /usr/local/bin/grain https://github.com/grain-lang/grain/releases/download/grain-v0.6.3/grain-linux-x64
        sudo chmod +x /usr/local/bin/grain
    -
      name: Install WABT
      run: sudo apt-get install -y wabt 
    -
      name: Build WASM files
      run: |
        make clean
        make
    -
      name: Login to GitHub's container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # -
    #   name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - 
    #   name: Add README to Docker Hub
    #   uses: peter-evans/dockerhub-description@v4
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     repository: ammo74/traefik-wabt
    #     short-description: "RouterOS /container for running traefik-wabt to flash Mikrotik devices on ARM/ARM64/X86"
    - 
      name: Build image and push image to ghcr.io
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        sbom: false
        provenance: false
        platforms: ${{ env.PLATFORMS }}
        tags: |
          ghcr.io/${{ github.repository }}:latest
        # ammo74/traefik-wabt:latest
        build-args: |
          GHCR_REPO=${{ github.repository }}
          GHCR_TAG=${{ steps.meta.outputs.tags }}
          GHCR_PLATFORMS=${{ env.PLATFORMS }}
    -
      name: Commit WASM files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git status
        git pull
        find ./plugins -name '*.wasm' | xargs git add
        find ./plugins -name '*.wat' | xargs git add
        git diff --quiet && git diff --staged --quiet || git commit -m "Update WASM from build [${{ github.workflow }}]"
        git push origin main
    - name: Save Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: |
          plugins/**
          cellar/**